- .gitignore
- gonawin/app.yaml
- gonawin/main.go
> add remote api to save/restore production datastore

- gonawin/app/components/root/root_controller.js
- gonawin/app/components/tournament/tournament_service.js
> Update Current Tournament section

- README.md
- controllers/users/users.go
- gonawin/app/app.js
- gonawin/app/components/dashboard/dashboard.html
- gonawin/app/components/dashboard/dashboard_controller.js
- gonawin/app/components/team/invite.html
- gonawin/app/components/team/team_controller.js
- gonawin/app/components/tournament/tournament_controller.js
- gonawin/app/components/user/user_controller.js
- gonawin/app/index.html
- gonawin/app/shared/about.html
- gonawin/app/shared/team_card.html
- gonawin/app/shared/themeSelector_service.js
- gonawin/app/shared/tournament_card.html
- gonawin/app/shared/user_card.html
> Use tinygraphs as avatar

- gonawin/app/components/search/search.html
- gonawin/app/components/search/search_controller.js
- gonawin/app/components/team/header.html
- gonawin/app/components/team/index.html
- gonawin/app/components/team/invite.html
- gonawin/app/components/team/tab_members.html
- gonawin/app/components/team/tab_tournaments.html
- gonawin/app/components/tournament/index.html
- gonawin/app/components/user/show.html
> bad diplay of cards when name is too long

- gonawin/app/app.css
- gonawin/app/components/dashboard/dashboard_team.html
- gonawin/app/components/dashboard/dashboard_tournament.html
- gonawin/app/components/dashboard/dashboard_user.html
> Bad display of dashboard on phone screen

- gonawin/app/app.css
> Issue with notification badge hover color

- controllers/tournaments/match.go
> Review Matches handler needs to be more generic

- controllers/tournaments/admin.go
- gonawin/app/app.css
- gonawin/app/components/tournament/tab_setteams.html
- gonawin/app/components/tournament/tournament_controller.js
- gonawin/app/components/tournament/tournament_service.js
- gonawin/main.go
- models/tournament_match.go
- models/tournament_phase.go
- models/tournament_team.go
> activate phase from admin Results tab

- gonawin/app/app.css
- gonawin/app/index.html
> use roboto font

- gonawin/app/app.css
- gonawin/app/components/authentication/facebook-signin.js
- gonawin/app/components/authentication/google-signin.js
- gonawin/app/components/authentication/twitter-signin.js
- gonawin/app/components/home/welcome.html
- gonawin/app/index.html
> Home page Improvement review

- gonawin/app/components/team/team_controller.js
- gonawin/app/components/tournament/header.html
- gonawin/app/components/tournament/tournament_controller.js
> Review leave button more explict

- controllers/tournaments/admin.go
> fix phase activation

- config/config.go
- controllers/tasks/doc.go
- gonawin/main.go
- helpers/auth/auth.go
- helpers/doc.go
- helpers/handlers/handlers.go
- helpers/log/log.go
- helpers/memcache/memcache.go
> add missing pkg documentation

- controllers/tournaments/subscription.go
set team as actor of the activity
> Team leaves tournament activity message is wrong 

- gonawin/app/components/tournament/tournament_controller.js
> score of tournament participants is wrong in ranking tab

- controllers/teams/teams.go
- gonawin/app/components/team/team_controller.js
- gonawin/app/shared/user_card.html
> Invite users to team

- models/activity.go
> skip empty activities

- controllers/tasks/delete.go
- controllers/users/users.go
- gonawin/main.go
- models/activity.go
> don't delete common activities

- controllers/tournaments/tournaments.go
- models/team.go
- models/tournament.go
- models/user.go
> make TournamentsByIds work in batch

- gonawin/app/components/team/show.html
- gonawin/app/components/tournament/show.html
- gonawin/app/components/tournament/tournament_controller.js
> no redirect when canceling tournament deletion

- controllers/invite/invite.go
- controllers/sessions/sessions.go
- controllers/tasks/delete.go
- controllers/tasks/invite.go
- controllers/teams/ranking.go
- controllers/tournaments/admin.go
- controllers/tournaments/calendar.go
- controllers/tournaments/match.go
- controllers/tournaments/tournaments.go
- controllers/users/search.go
- extract/extract.go
- models/accuracy.go
- models/activity.go
- models/predict.go
- models/price.go
- models/score.go
- models/search.go
- models/team_invid.go
- models/tournament_match.go
- models/tournament_score.go
- models/tournament_team.go
- models/user_invid.go
> clean info messages in backend

- gonawin/queue.yaml
> set task_retry_limit to 1

- controllers/teams/search.go
- models/team.go
- models/user.go
> use GetMulti to fetch teams

- models/team.go
- models/team_test.go
issue 728 should be merged first
> Issue 729 test Team Destroy

- models/team_test.go
needs that 729 and 728 are merged first
> Issue 730 test FindTeams

- models/team_test.go
- models/user_test.go
- test/errors.go
> create test package called gonawintest use ErrString

- models/team_test.go
- models/tournament_team_test.go
> Issue 731 test Team.TeamById

- models/team.go
- models/team_test.go
- models/tournament_team_test.go
> Issue 732 TestTeamKeyById

- models/team.go
- models/team_test.go
- models/tournament_team_test.go
issue #733 
needs issue #732 and #731 to be merged in before
> Issue 733 test team.Update

- models/team_test.go
- models/user_test.go
> Issue 736 TeamsByIds

- models/activity_test.go
- models/team_test.go
- models/tournament_test.go
- models/user_test.go
> rename test functions 

- models/team.go
- models/team_test.go
> Issue 735 TestGetNotJoinedTeams

- models/team.go
- models/team_test.go
* team.Joined
* team.Join
* Team.Leave
* IsTeamAdmin
> Team tests

- models/team_test.go
> test FindAllTeams

- models/team.go
- models/team_test.go
> Issue 801 test TestGetWordFrequencyForTeam
